### ISSUE TITLE
"I should see an email..." should look for any email, not just the latest email

### ISSUE THREAD

**Issue by rpkamp** [rpkamp/mailhog-behat-extension#28]
That's what the description actually says. Otherwise it should have been "I should see the latest email ..."

**Comment by sensespidey** [comment]
I ran across this problem, and implemented a simple workaround for my purposes, using a new step function like this:

```
   /**
     * @Then /^I should see an email somewhere with subject "(?P<subject>[^"]*)"$/
     */
    public function iShouldSeeAnEmailWithSubjectSomewhere(string $subject) {
      foreach ($this->mailhogClient->findAllMessages() as $message) {
        if (!empty($subject) && $subject !== $message->subject) {
          continue;
        }

        return;
      }

      throw new RuntimeException(
        sprintf( 'No message found with subject "%s"', $subject )
      );
    }
```
Obviously this only handles looking for an email with a given subject, and I'm not sure how best to extend it to the general case addressed by `iShouldSeeAnEmailWithSubjectAndBodyFromToRecipient()`, but I believe this approach of calling `$this->mailhogClient->findAllMessages()` should work.

**Comment by rpkamp** [comment]
Released: https://github.com/rpkamp/mailhog-behat-extension/releases/tag/0.6.0
