### ISSUE TITLE
Request option to view the last added email

### ISSUE THREAD

**Issue by HVSoftware** [rpkamp/mailhog-behat-extension#51]
I'm working on a project and I have an issue. I see there is one email inside my inbox. Only the second rule is failing. 

    And there should be 1 email in my inbox
    And I should see an email with subject "subject.create_something" from "info@some-company.nl"

I do not see a rule where i'm able to print out the last message.

I know you have `print last response` in Mink. Can we have a `print last email`?

I'm able to create a PR. 

PS I was able to fix the problem.

**Comment by rpkamp** [comment]
You can always check mailhog in your browser after the scenario to see what -if any- mails are there, that seems easier  :slightly_smiling_face:
